// Real NW Calgary mechanic shops with geocoordinates
// Sources: Bowest Motors, Dalhousie Auto (Bumper to Bumper), Joyride Automotive,
//          Silver Springs Automotive, Minit-Tune Crowfoot, Midas 16 Ave NW

export const vendors = [
  {
    id: 'v001',
    businessName: 'Bowest Motors',
    address: '8305 Bowness Rd NW, Calgary, AB T3B 0H4',
    neighbourhood: 'Bowness',
    lat: 51.0852, lng: -114.1861,
    distance: 3.2,
    rating: 4.7,
    reviewCount: 142,
    insuranceVerified: true,
    services: ['Oil Change', 'Engine Diagnostic', 'Brake Pad Replacement', 'Transmission Service', 'Tire Rotation'],
    priceRange: [75, 380],
    modes: ['instore'],
    nextAvailable: 'Today 2:00 PM',
    phone: '(403) 288-4142',
    emoji: '🏪',
    yearsOpen: 67,
  },
  {
    id: 'v002',
    businessName: 'Dalhousie Auto Service',
    address: '5302 Northland Dr NW, Calgary, AB T2L 2K4',
    neighbourhood: 'Dalhousie',
    lat: 51.1010, lng: -114.1413,
    distance: 1.8,
    rating: 4.5,
    reviewCount: 89,
    insuranceVerified: true,
    services: ['Oil Change', 'Brake Inspection', 'Brake Pad Replacement', 'Battery Test & Replace', 'Fluid Top-Up'],
    priceRange: [49, 220],
    modes: ['instore'],
    nextAvailable: 'Today 11:00 AM',
    phone: '(403) 289-5581',
    emoji: '🔧',
    yearsOpen: 18,
  },
  {
    id: 'v003',
    businessName: 'Joyride Automotive',
    address: '4645 Varsity Dr NW, Calgary, AB T3A 0Z7',
    neighbourhood: 'Varsity',
    lat: 51.0905, lng: -114.1684,
    distance: 2.4,
    rating: 4.9,
    reviewCount: 207,
    insuranceVerified: true,
    services: ['Oil Change', 'Engine Diagnostic', 'Brake Inspection', 'Brake Pad Replacement', 'AC Service', 'Tire Rotation'],
    priceRange: [69, 320],
    modes: ['instore', 'mobile'],
    nextAvailable: 'Today 3:00 PM',
    phone: '(403) 452-2112',
    emoji: '⚡',
    yearsOpen: 12,
  },
  {
    id: 'v004',
    businessName: 'Silver Springs Automotive',
    address: '5858 Silver Springs Blvd NW, Calgary, AB T3B 4N7',
    neighbourhood: 'Silver Springs',
    lat: 51.0982, lng: -114.2036,
    distance: 5.1,
    rating: 4.6,
    reviewCount: 78,
    insuranceVerified: true,
    services: ['Oil Change', 'Tire Rotation', 'Windshield Wiper Replace', 'Fluid Top-Up', 'Battery Test & Replace'],
    priceRange: [39, 160],
    modes: ['instore', 'mobile'],
    nextAvailable: 'Tomorrow 9:00 AM',
    phone: '(403) 241-6100',
    emoji: '🚗',
    yearsOpen: 25,
  },
  {
    id: 'v005',
    businessName: 'Minit-Tune & Brake (Crowfoot)',
    address: '152 Crowfoot Gate NW, Calgary, AB T3G 3L1',
    neighbourhood: 'Crowfoot',
    lat: 51.1072, lng: -114.1886,
    distance: 6.3,
    rating: 4.3,
    reviewCount: 165,
    insuranceVerified: true,
    services: ['Oil Change', 'Brake Pad Replacement', 'Brake Inspection', 'Tire Rotation', 'Fluid Top-Up'],
    priceRange: [49, 250],
    modes: ['instore'],
    nextAvailable: 'Today 4:30 PM',
    phone: '(403) 241-3444',
    emoji: '🔩',
    yearsOpen: 30,
  },
  {
    id: 'v006',
    businessName: 'Midas Auto Service (16 Ave)',
    address: '624 16 Ave NW, Calgary, AB T2M 0J7',
    neighbourhood: 'Capitol Hill',
    lat: 51.0572, lng: -114.0901,
    distance: 1.1,
    rating: 4.2,
    reviewCount: 234,
    insuranceVerified: true,
    services: ['Oil Change', 'Brake Inspection', 'Brake Pad Replacement', 'Engine Diagnostic', 'Tire Rotation', 'Battery Test & Replace'],
    priceRange: [59, 290],
    modes: ['instore'],
    nextAvailable: 'Today 1:30 PM',
    phone: '(403) 283-3666',
    emoji: '🏎',
    yearsOpen: 22,
  },
]

export const serviceCategories = [
  'Oil Change', 'Brake Inspection', 'Brake Pad Replacement',
  'Engine Diagnostic', 'Tire Rotation', 'Battery Test & Replace',
  'Transmission Service', 'AC Service', 'Fluid Top-Up',
]

export const myVehicle = {
  vin: '1HGBH41JXMN109186',
  year: 2021,
  make: 'Honda',
  model: 'Civic',
  trim: 'LX Sedan',
  engine: '1.5L Turbo I4',
  decoded: true,
}

// Sarah Chen's location: near Brentwood NW Calgary
export const MY_LOCATION = { lat: 51.0955, lng: -114.1280 }

export const myBookings = [
  {
    id: 'b901',
    vendorId: 'v001',
    vendorName: 'Bowest Motors',
    service: 'Oil Change',
    date: '2026-06-08',
    time: '09:00',
    price: 79,
    status: 'done',
    mode: 'instore',
    vehicle: '2021 Honda Civic',
  },
  {
    id: 'b902',
    vendorId: 'v002',
    vendorName: 'Dalhousie Auto Service',
    service: 'Brake Inspection',
    date: '2026-06-09',
    time: '10:00',
    price: 49,
    status: 'accepted',
    mode: 'instore',
    vehicle: '2021 Honda Civic',
  },
]

export const aiConversation = [
  { role: 'assistant', text: "Hi! I'm MechFind AI. Share your VIN and describe your issue — I'll triage it and route you to the right shop if needed." },
  { role: 'user', text: '1HGBH41JXMN109186' },
  { role: 'assistant', text: "✅ VIN decoded: **2021 Honda Civic LX Sedan, 1.5L Turbo I4**. Got it — what's the issue?" },
  { role: 'user', text: 'I hear a grinding noise when I brake, especially at low speed' },
  { role: 'assistant', text: "⚠️ **Severity: Safety-Critical** — Grinding brakes typically mean worn brake pads or damaged rotors. Metal-on-metal contact that worsens quickly.\n\n**Do not delay this.** I've found nearby shops with same-day availability for a brake inspection." },
]
